In [3]:
import numpy as np
import pandas as pd

In [13]:
a = np.array([5, 7, 19, 20, 32, 2, 5, 8, 13, 4])
a_series = pd.Series(a,index=["A","B", "C", "D", "E", "F", "G", "H", "I", "J"]) 
print(f'\na_series["A"]:\n{a_series["A"]}')
print(f"\na_series:\n{a_series}")
b = np.array([[4,2,3,8],[1,5,7,4],[6,3,9,3],[7,8,4,3]])
b_df = pd.DataFrame(b,columns=["A","B", "C", "D"], index=["I", "II", "III", "IV"]) 
print(f'\nb_df["II"]:\n{b_df.loc["II"]}')
print(f"\nb_df:\n{b_df}")

a_series["A"]:
5

a_series:
A     5
B     7
C    19
D    20
E    32
F     2
G     5
H     8
I    13
J     4
dtype: int32

b_df["II"]:
A    1
B    5
C    7
D    4
Name: II, dtype: int32

b_df:
     A  B  C  D
I    4  2  3  8
II   1  5  7  4
III  6  3  9  3
IV   7  8  4  3

In [14]:
data = np.reshape(np.arange(9), (3,3))
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
df1 = pd.DataFrame(data)
df1

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [17]:
df1.columns = ["A", "B", "C"]
df1.index = ["first", "second", "third"]
df1

        A  B  C
first   0  1  2
second  3  4  5
third   6  7  8

In [18]:
df2 = pd.DataFrame(np.random.rand(3,3))
df2.columns = ["D", "E", "F"]
df2.index = ["first", "second", "third"]
df2

               D         E         F
first   0.552953  0.161485  0.929489
second  0.502133  0.085179  0.460426
third   0.919087  0.079233  0.133142

In [19]:
df3 = pd.concat([df1,df2],axis=1)
df3

        A  B  C         D         E         F
first   0  1  2  0.552953  0.161485  0.929489
second  3  4  5  0.502133  0.085179  0.460426
third   6  7  8  0.919087  0.079233  0.133142

In [20]:
df3.dtypes

A      int32
B      int32
C      int32
D    float64
E    float64
F    float64
dtype: object

In [21]:
df3.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [22]:
df3["F"]

first     0.929489
second    0.460426
third     0.133142
Name: F, dtype: float64

In [23]:
df3.loc["first"]

A    0.000000
B    1.000000
C    2.000000
D    0.552953
E    0.161485
F    0.929489
Name: first, dtype: float64

In [24]:
df3.iloc[0]

A    0.000000
B    1.000000
C    2.000000
D    0.552953
E    0.161485
F    0.929489
Name: first, dtype: float64

In [25]:
df3.iloc[2][2]

C:\Users\pat\AppData\Local\Temp\ipykernel_10624\1482261536.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df3.iloc[2][2]

8.0