In [1]:
import numpy as np
import pandas as pd

In [2]:
!pwd

/cygdrive/c/Users/pat

In [10]:
# read in movie CSV data and set Title as index column
df1 = pd.read_csv("IMDB-Movie_lesson_2_3.csv", index_col="Title")

In [11]:
# verify data was read in - head by default reads 1st lines
df1.head()

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [12]:
# read last 2 lines
df1.tail(2)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [15]:
# rename columns with lowercase and shorter names
df1.columns = ['rank','genre','desc','dir','actor','year','length','rating','votes','rev','mscore']
df1.head(2)

,rank,genre,desc,dir,actor,year,length,rating,votes,rev,mscore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0

In [16]:
# change 'index' name to 'title' (lowercase)
df1.index.name = 'title'

In [17]:
# use info() to report column related info (column name, non-null count, datatype)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   rank    1000 non-null   int64
 1   genre   1000 non-null   object
 2   desc    1000 non-null   object
 3   dir     1000 non-null   object
 4   actor   1000 non-null   object
 5   year    1000 non-null   int64
 6   length  1000 non-null   int64
 7   rating  1000 non-null   float64
 8   votes   1000 non-null   int64
 9   rev     872 non-null    float64
 10  mscore  936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

In [18]:
# use describe() to report the count, mean, std deviation, min, max, etc
df1.describe()

,rank,year,length,rating,votes,rev,mscore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

In [20]:
# use 'share' report number of columns and rows in dataset
df1.shape

(1000, 11)

In [21]:
# report the number of non-null values
df1.isnull().sum()

rank        0
genre       0
desc        0
dir         0
actor       0
year        0
length      0
rating      0
votes       0
rev       128
mscore     64
dtype: int64

In [23]:
# replace 'rev' column NaN (not a number) values with the 'rev' mean value
df1['rev'].fillna(df1['rev'].mean(),inplace=True)
# replace 'mscore' [metascore] column NaN (not a number) values with the 'mscore' mean value
df1['mscore'].fillna(df1['mscore'].mean(),inplace=True)

In [24]:
# after changs, report the number of non-null values
df1.isnull().sum()

rank      0
genre     0
desc      0
dir       0
actor     0
year      0
length    0
rating    0
votes     0
rev       0
mscore    0
dtype: int64

In [25]:
# drop the rank column - Note: axis=0 impacts rows, and axis=1 impacts the columns
df1.drop(['rank'],axis=1,inplace=True)

In [28]:
# find mean of the movies grouped by year
df1.groupby(['year'])[['length','rating','votes','rev','mscore']].mean()

          length    rating          votes         rev     mscore
year
2006  120.840909  7.125000  269289.954545   86.144835  64.044435
2007  121.622642  7.133962  244331.037736   87.510481  63.771609
2008  110.826923  6.784615  275505.384615   98.772623  57.499137
2009  116.117647  6.960784  255780.647059  110.276186  57.195492
2010  111.133333  6.826667  252782.316667  103.975319  59.383084
2011  114.603175  6.838095  240790.301587   87.538355  61.506749
2012  119.109375  6.925000  285226.093750  107.973281  61.077658
2013  116.065934  6.812088  219049.648352   86.984496  58.559618
2014  114.489796  6.837755  203930.224490   84.992097  57.366889
2015  114.496063  6.602362  115726.220472   78.862278  57.101891
2016  107.373737  6.436700   48591.754209   63.446588  58.352075

In [29]:
# find mean of the movies grouped by year sorted by revenue
df1.groupby(['year'])[['length','rating','votes','rev','mscore']].mean().sort_values(by=['rev'], ascending=False)

          length    rating          votes         rev     mscore
year
2009  116.117647  6.960784  255780.647059  110.276186  57.195492
2012  119.109375  6.925000  285226.093750  107.973281  61.077658
2010  111.133333  6.826667  252782.316667  103.975319  59.383084
2008  110.826923  6.784615  275505.384615   98.772623  57.499137
2011  114.603175  6.838095  240790.301587   87.538355  61.506749
2007  121.622642  7.133962  244331.037736   87.510481  63.771609
2013  116.065934  6.812088  219049.648352   86.984496  58.559618
2006  120.840909  7.125000  269289.954545   86.144835  64.044435
2014  114.489796  6.837755  203930.224490   84.992097  57.366889
2015  114.496063  6.602362  115726.220472   78.862278  57.101891
2016  107.373737  6.436700   48591.754209   63.446588  58.352075

In [30]:
# sort 2012 movies by revenue
df1[df1['year'] == 2012].sort_values(by=['rev'], ascending=False)

,genre,desc,dir,actor,year,length,rating,votes,rev,mscore
title,,,,,,,,,,
The Avengers,"Action,Sci-Fi",Earth's mightiest heroes must come together an...,Joss Whedon,"Robert Downey Jr., Chris Evans, Scarlett Johan...",2012,143,8.1,1045588,623.28,69.0
The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0
The Hunger Games,"Adventure,Sci-Fi,Thriller",Katniss Everdeen voluntarily takes her younger...,Gary Ross,"Jennifer Lawrence, Josh Hutcherson, Liam Hemsw...",2012,142,7.2,735604,408.00,68.0
Skyfall,"Action,Adventure,Thriller",Bond's loyalty to M is tested when her past co...,Sam Mendes,"Daniel Craig, Javier Bardem, Naomie Harris, Ju...",2012,143,7.8,547386,304.36,81.0
The Hobbit: An Unexpected Journey,"Adventure,Fantasy","A reluctant hobbit, Bilbo Baggins, sets out to...",Peter Jackson,"Martin Freeman, Ian McKellen, Richard Armitage...",2012,169,7.9,668651,303.00,58.0
...,...,...,...,...,...,...,...,...,...,...
Spring Breakers,Drama,Four college girls hold up a restaurant in ord...,Harmony Korine,"Vanessa Hudgens, Selena Gomez, Ashley Benson,R...",2012,94,5.3,114290,14.12,63.0
Dredd,"Action,Sci-Fi","In a violent, futuristic city where the police...",Pete Travis,"Karl Urban, Olivia Thirlby, Lena Headey, Rache...",2012,95,7.1,213764,13.40,59.0
Anna Karenina,"Drama,Romance","In late-19th-century Russian high society, St....",Joe Wright,"Keira Knightley, Jude Law, Aaron Taylor-Johnso...",2012,129,6.6,75291,12.80,63.0
Jagten,Drama,"A teacher lives a lonely life, all the while s...",Thomas Vinterberg,"Mads Mikkelsen, Thomas Bo Larsen, Annika Wedde...",2012,115,8.3,192263,0.61,76.0
The First Time,"Comedy,Drama,Romance",A shy senior and a down-to-earth junior fall i...,Jon Kasdan,"Dylan O'Brien, Britt Robertson, Victoria Justi...",2012,95,6.9,54027,0.02,55.0

In [31]:
# find highest rated movies in the Comedy and Action genres
df1[df1['genre'].isin(['Comedy', 'Action'])].sort_values(by=['rating'], ascending=False)

,genre,desc,dir,actor,year,length,rating,votes,rev,mscore
title,,,,,,,,,,
The Hangover,Comedy,Three buddies wake up from a bachelor party in...,Todd Phillips,"Zach Galifianakis, Bradley Cooper, Justin Bart...",2009,100,7.8,611563,277.310000,73.000000
Superbad,Comedy,Two co-dependent high school seniors are force...,Greg Mottola,"Michael Cera, Jonah Hill, Christopher Mintz-Pl...",2007,113,7.6,442082,121.460000,76.000000
Boyka: Undisputed IV,Action,In the fourth installment of the fighting fran...,Todor Chapkanov,"Scott Adkins, Teodora Duhovnikova, Alon Aboutb...",2016,86,7.4,10428,82.956376,58.985043
Everybody Wants Some!!,Comedy,"In 1980, a group of college baseball players n...",Richard Linklater,"Blake Jenner, Tyler Hoechlin, Ryan Guzman,Zoey...",2016,117,7.0,36312,3.370000,83.000000
Step Brothers,Comedy,Two aimless middle-aged losers still living at...,Adam McKay,"Will Ferrell, John C. Reilly, Mary Steenburgen...",2008,98,6.9,223065,100.470000,51.000000
Paris pieds nus,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,82.956376,58.985043
Project X,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.720000,48.000000
American Reunion,Comedy,"Jim, Michelle, Stifler, and their friends reun...",Jon Hurwitz,"Jason Biggs, Alyson Hannigan,Seann William Sco...",2012,113,6.7,178471,56.720000,49.000000
Entourage,Comedy,"Movie star Vincent Chase, together with his bo...",Doug Ellin,"Adrian Grenier, Kevin Connolly, Jerry Ferrara,...",2015,104,6.6,64557,32.360000,38.000000
The Interview,Comedy,Dave Skylark and his producer Aaron Rapoport r...,Evan Goldberg,"James Franco, Seth Rogen, Randall Park, Lizzy ...",2014,112,6.6,261536,6.110000,52.000000
Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.390000,30.000000
The DUFF,Comedy,A high school senior instigates a social pecki...,Ari Sandel,"Mae Whitman, Bella Thorne, Robbie Amell, Allis...",2015,101,6.5,57874,34.020000,56.000000
The Dictator,Comedy,The heroic story of a dictator who risked his ...,Larry Charles,"Sacha Baron Cohen, Anna Faris, John C. Reilly,...",2012,83,6.4,225394,59.620000,58.000000
Neighbors,Comedy,After they are forced to live next to a frater...,Nicholas Stoller,"Seth Rogen, Rose Byrne, Zac Efron, Lisa Kudrow",2014,97,6.4,236500,150.060000,68.000000
Mindhorn,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,82.956376,71.000000
The Internship,Comedy,Two salesmen whose careers have been torpedoed...,Shawn Levy,"Vince Vaughn, Owen Wilson, Rose Byrne, Aasif M...",2013,119,6.3,166342,44.670000,42.000000
Why Him?,Comedy,A holiday gathering threatens to go off the ra...,John Hamburg,"Zoey Deutch, James Franco, Tangie Ambrose,Cedr...",2016,111,6.3,48123,60.310000,39.000000
Bad Moms,Comedy,When three overworked and under-appreciated mo...,Jon Lucas,"Mila Kunis, Kathryn Hahn, Kristen Bell,Christi...",2016,100,6.2,66540,113.080000,60.000000
Good Kids,Comedy,Four high school students look to redefine the...,Chris McCoy,"Zoey Deutch, Nicholas Braun, Mateo Arias, Isra...",2016,86,6.1,3843,82.956376,86.000000
Dirty Grandpa,Comedy,"Right before his wedding, an uptight guy is tr...",Dan Mazer,"Robert De Niro, Zac Efron, Zoey Deutch, Aubrey...",2016,102,6.0,75137,35.540000,18.000000
Grown Ups,Comedy,After their high school basketball coach passe...,Dennis Dugan,"Adam Sandler, Salma Hayek, Kevin James, Chris ...",2010,102,6.0,190385,162.000000,30.000000
Sisters,Comedy,Two sisters decide to throw one last house par...,Jason Moore,"Amy Poehler, Tina Fey, Maya Rudolph, Ike Barin...",2015,118,6.0,50241,87.030000,58.000000
Office Christmas Party,Comedy,When his uptight CEO sister threatens to shut ...,Josh Gordon,"Jason Bateman, Olivia Munn, T.J. Miller,Jennif...",2016,105,5.8,30761,54.730000,42.000000
Neighbors 2: Sorority Rising,Comedy,When their new next-door neighbors turn out to...,Nicholas Stoller,"Seth Rogen, Rose Byrne, Zac Efron, Chloë Grace...",2016,92,5.7,76327,55.290000,58.000000
Folk Hero & Funny Guy,Comedy,A successful singer-songwriter hatches a plan ...,Jeff Grace,"Alex Karpovsky, Wyatt Russell, Meredith Hagner...",2016,88,5.6,220,82.956376,63.000000
Couples Retreat,Comedy,A comedy centered around four couples who sett...,Peter Billingsley,"Vince Vaughn, Malin Akerman, Jon Favreau, Jaso...",2009,113,5.5,86417,109.180000,23.000000
Grown Ups 2,Comedy,After moving his family back to his hometown t...,Dennis Dugan,"Adam Sandler, Kevin James, Chris Rock, David S...",2013,101,5.4,114482,133.670000,19.000000
The Comedian,Comedy,A look at the life of an aging insult comic na...,Taylor Hackford,"Robert De Niro, Leslie Mann, Danny DeVito, Edi...",2016,120,5.4,1954,1.660000,40.000000
The Boss,Comedy,A titan of industry is sent to prison after sh...,Ben Falcone,"Melissa McCarthy, Kristen Bell, Peter Dinklage...",2016,99,5.4,29642,63.030000,40.000000
Amateur Night,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,82.956376,38.000000
Kickboxer: Vengeance,Action,A kick boxer is out to avenge his brother.,John Stockwell,"Dave Bautista, Alain Moussi, Gina Carano, Jean...",2016,90,4.9,6809,131.560000,37.000000
Chalk It Up,Comedy,When a super girly-girl is dumped by her boyfr...,Hisonni Johnson,"Maddy Curley, John DeLuca, Nikki SooHoo, Drew ...",2016,90,4.8,499,82.956376,58.985043
Zoolander 2,Comedy,Derek and Hansel are lured into modeling again...,Ben Stiller,"Ben Stiller, Owen Wilson, Penélope Cruz, Will ...",2016,102,4.7,48297,28.840000,34.000000
Disaster Movie,Comedy,"Over the course of one evening, an unsuspectin...",Jason Friedberg,"Carmen Electra, Vanessa Lachey,Nicole Parker, ...",2008,87,1.9,77207,14.170000,15.000000

In [34]:
# find the best rated (in the top 99%) with the lowest revenue movies (in the bottom 25%)
df1[(df1['rating'] > df1['rating'].quantile(0.99)) & (df1['rev'] < df1['rev'].quantile(0.25))]

,genre,desc,dir,actor,year,length,rating,votes,rev,mscore
title,,,,,,,,,,
Kimi no na wa,"Animation,Drama,Fantasy",Two strangers find themselves linked in a biza...,Makoto Shinkai,"Ryûnosuke Kamiki, Mone Kamishiraishi, Ryô Nari...",2016,106,8.6,34110,4.68,79.000000
Dangal,"Action,Biography,Drama",Former wrestler Mahavir Singh Phogat and his t...,Nitesh Tiwari,"Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh,...",2016,161,8.8,48969,11.15,58.985043
The Intouchables,"Biography,Comedy,Drama",After he becomes a quadriplegic from a paragli...,Olivier Nakache,"François Cluzet, Omar Sy, Anne Le Ny, Audrey F...",2011,112,8.6,557965,13.18,57.000000