In [1]:
import numpy as np
import pandas as pd

In [2]:
# load earthquake dataset
df1 = pd.read_csv("earthquakes-dataset_lesson3_3.csv")
# verify data was loaded
# report number of columns and rows
print(f"df1.shape: {df1.shape}")
# report 1st 3 lines plus column labels
print("\ndf1.head(3):")
df1.head(3)

df1.shape: (23412, 21)

df1.head(3):

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic

In [3]:
date_demo = "21st of July 2000"
print (f"date_demo: {date_demo}")
date_demo_datetime = pd.to_datetime(date_demo)
print (f"date_demo_datetime: {date_demo_datetime}")

date_demo: 21st of July 2000
date_demo_datetime: 2000-07-21 00:00:00

In [4]:
# create Datetime field which merges 'Date' and 'Time' columns 
# Note: add "errors = 'coerce'" argument so that invalid parsing results in empty values instead of failing
df1['Datetime'] =  pd.to_datetime(df1['Date'] + ' ' + df1['Time'], errors = 'coerce')
# verify new Datetime column
df1.head(3)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status,Datetime
0,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-02 13:44:18
1,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-04 11:29:49
2,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic,1965-01-05 18:05:58

In [5]:
# display Datetime in 1st row
print (f"df1['Datetime'][0]: {df1['Datetime'][0]}")
# display some 1st datetime info: %A (day of the week), %a (short form of day of the week), %B (month)
df1['Datetime'][0].strftime('%A or %a and is %B')

df1['Datetime'][0]: 1965-01-02 13:44:18

'Saturday or Sat and is January'

In [6]:
# set Datetime column as the index field
df1 = df1.set_index(['Datetime'])
# verify index change
df1.head(3)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
Datetime,,,,,,,,,,,,,,,,,,,,,
1965-01-02 13:44:18,01/02/1965,13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-04 11:29:49,01/04/1965,11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-05 18:05:58,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic

In [7]:
# check the datatypes set when CSV file was read in (sometimes not set correctly)
df1.dtypes

Date                           object
Time                           object
Latitude                      float64
Longitude                     float64
Type                           object
Depth                         float64
Depth Error                   float64
Depth Seismic Stations        float64
Magnitude                     float64
Magnitude Type                 object
Magnitude Error               float64
Magnitude Seismic Stations    float64
Azimuthal Gap                 float64
Horizontal Distance           float64
Horizontal Error              float64
Root Mean Square              float64
ID                             object
Source                         object
Location Source                object
Magnitude Source               object
Status                         object
dtype: object

In [8]:
# convert Depth column from floating point to integer (using astype() method)
df1['Depth'] = df1['Depth'].astype(int)
# verify change
df1.head(3)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
Datetime,,,,,,,,,,,,,,,,,,,,,
1965-01-02 13:44:18,01/02/1965,13:44:18,19.246,145.616,Earthquake,131,NaN,NaN,6.0,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-04 11:29:49,01/04/1965,11:29:49,1.863,127.352,Earthquake,80,NaN,NaN,5.8,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-05 18:05:58,01/05/1965,18:05:58,-20.579,-173.972,Earthquake,20,NaN,NaN,6.2,MW,...,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic

In [9]:
# re-read CSV file, this time, merging 'Date' and 'Time' columns
df1 = pd.read_csv("earthquakes-dataset_lesson3_3.csv", index_col= 0, parse_dates= [['Date', 'Time']])
# verify updated dataframe
df1.head(3)

,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,Magnitude Error,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
Date_Time,,,,,,,,,,,,,,,,,,,
01/02/1965 13:44:18,19.246,145.616,Earthquake,131.6,NaN,NaN,6.0,MW,NaN,NaN,NaN,NaN,NaN,NaN,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
01/04/1965 11:29:49,1.863,127.352,Earthquake,80.0,NaN,NaN,5.8,MW,NaN,NaN,NaN,NaN,NaN,NaN,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
01/05/1965 18:05:58,-20.579,-173.972,Earthquake,20.0,NaN,NaN,6.2,MW,NaN,NaN,NaN,NaN,NaN,NaN,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic

In [10]:
# check index type (object or datetime?)
df1.index

Index(['01/02/1965 13:44:18', '01/04/1965 11:29:49', '01/05/1965 18:05:58',
       '01/08/1965 18:49:43', '01/09/1965 13:32:50', '01/10/1965 13:36:32',
       '01/12/1965 13:32:25', '01/15/1965 23:17:42', '01/16/1965 11:32:37',
       '01/17/1965 10:43:17',
       ...
       '12/24/2016 03:58:55', '12/25/2016 14:22:27', '12/25/2016 14:32:13',
       '12/27/2016 23:20:56', '12/28/2016 08:18:01', '12/28/2016 08:22:12',
       '12/28/2016 09:13:47', '12/28/2016 12:38:51', '12/29/2016 22:30:19',
       '12/30/2016 20:08:28'],
      dtype='object', name='Date_Time', length=23412)

In [11]:
# df1.index return 'object' type, so convert index to 'datetime' type
df1.index = pd.to_datetime(df1.index, errors='coerce')
# verify df.index converted to 'datetime' type
df1.index

DatetimeIndex(['1965-01-02 13:44:18', '1965-01-04 11:29:49',
               '1965-01-05 18:05:58', '1965-01-08 18:49:43',
               '1965-01-09 13:32:50', '1965-01-10 13:36:32',
               '1965-01-12 13:32:25', '1965-01-15 23:17:42',
               '1965-01-16 11:32:37', '1965-01-17 10:43:17',
               ...
               '2016-12-24 03:58:55', '2016-12-25 14:22:27',
               '2016-12-25 14:32:13', '2016-12-27 23:20:56',
               '2016-12-28 08:18:01', '2016-12-28 08:22:12',
               '2016-12-28 09:13:47', '2016-12-28 12:38:51',
               '2016-12-29 22:30:19', '2016-12-30 20:08:28'],
              dtype='datetime64[ns]', name='Date_Time', length=23412, freq=None)

In [12]:
# used 'info()' to determine columns with null values
df1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23412 entries, 1965-01-02 13:44:18 to 2016-12-30 20:08:28
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Latitude                    23412 non-null  float64
 1   Longitude                   23412 non-null  float64
 2   Type                        23412 non-null  object
 3   Depth                       23412 non-null  float64
 4   Depth Error                 4461 non-null   float64
 5   Depth Seismic Stations      7097 non-null   float64
 6   Magnitude                   23412 non-null  float64
 7   Magnitude Type              23409 non-null  object
 8   Magnitude Error             327 non-null    float64
 9   Magnitude Seismic Stations  2564 non-null   float64
 10  Azimuthal Gap               7299 non-null   float64
 11  Horizontal Distance         1604 non-null   float64
 12  Horizontal Error            1156 non-null   float64
 13  Root Mean Square            17352 non-null  float64
 14  ID                          23412 non-null  object
 15  Source                      23412 non-null  object
 16  Location Source             23412 non-null  object
 17  Magnitude Source            23412 non-null  object
 18  Status                      23412 non-null  object
dtypes: float64(12), object(7)
memory usage: 3.6+ MB

In [13]:
# drop all the columns (axis=1) with null values in some rows using 'dropna()'
df1 = df1.dropna(axis = 1)
# check 1st 3 rows
df1.head(3)

,Latitude,Longitude,Type,Depth,Magnitude,ID,Source,Location Source,Magnitude Source,Status
Date_Time,,,,,,,,,,
1965-01-02 13:44:18,19.246,145.616,Earthquake,131.6,6.0,ISCGEM860706,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-04 11:29:49,1.863,127.352,Earthquake,80.0,5.8,ISCGEM860737,ISCGEM,ISCGEM,ISCGEM,Automatic
1965-01-05 18:05:58,-20.579,-173.972,Earthquake,20.0,6.2,ISCGEM860762,ISCGEM,ISCGEM,ISCGEM,Automatic

In [14]:
# use 'info()' to show remain colunms and if all rows with null values have been removed
df1.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 23412 entries, 1965-01-02 13:44:18 to 2016-12-30 20:08:28
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Latitude          23412 non-null  float64
 1   Longitude         23412 non-null  float64
 2   Type              23412 non-null  object
 3   Depth             23412 non-null  float64
 4   Magnitude         23412 non-null  float64
 5   ID                23412 non-null  object
 6   Source            23412 non-null  object
 7   Location Source   23412 non-null  object
 8   Magnitude Source  23412 non-null  object
 9   Status            23412 non-null  object
dtypes: float64(4), object(6)
memory usage: 2.0+ MB

In [15]:
# create a new dataframe, df2, with only the most important columns
df2 = df1[['Latitude', 'Longitude', 'Type', 'Depth', 'Magnitude']]
# check results (3 rows) 'sample()' which randomly picks row
df2.sample(3)

                     Latitude  Longitude        Type  Depth  Magnitude
Date_Time
1989-02-10 12:59:31     2.429    126.700  Earthquake   33.0        5.6
2000-01-19 07:09:34    36.372     70.379  Earthquake  206.9        6.0
1986-10-14 13:07:19   -43.142     41.776  Earthquake   10.0        6.2

In [16]:
# use 'unique()' to check the unique values in the 'Type' column
df2.Type.unique()

array(['Earthquake', 'Nuclear Explosion', 'Explosion', 'Rock Burst'],
      dtype=object)

In [17]:
# determine earthquake with largest 'Magnitude' in dataset
df2[df2.Type == "Earthquake"].Magnitude.max()

9.1

In [18]:
# determine earthquake with largest 'Depth' (reported in KM) in dataset
df2[df2.Type == "Earthquake"].Depth.max()

700.0

In [19]:
# determine earthquake with smallest 'Depth' in dataset
df2[df2.Type == "Earthquake"].Depth.min()

-1.1

In [20]:
# How many earthquakes in dataset (exmine Type "Earthquake" in results )
df2.Type.value_counts()

Type
Earthquake           23232
Nuclear Explosion      175
Explosion                4
Rock Burst               1
Name: count, dtype: int64

In [21]:
# determine average Magnitude of earthquakes in 12 month periods using 'resample()' with mean()
df2['Magnitude'][df2.Type == 'Earthquake'].resample('12M').mean()

Date_Time
1965-01-31    6.123077
1966-01-31    6.003254
1967-01-31    6.042218
1968-01-31    6.019835
1969-01-31    6.089216
1970-01-31    6.001246
1971-01-31    6.028329
1972-01-31    5.988542
1973-01-31    5.920844
1974-01-31    5.804455
1975-01-31    5.829370
1976-01-31    5.844240
1977-01-31    5.824279
1978-01-31    5.782692
1979-01-31    5.821320
1980-01-31    5.819308
1981-01-31    5.866860
1982-01-31    5.863133
1983-01-31    5.807872
1984-01-31    5.875708
1985-01-31    5.852311
1986-01-31    5.891922
1987-01-31    5.872316
1988-01-31    5.894343
1989-01-31    5.850533
1990-01-31    5.836157
1991-01-31    5.870382
1992-01-31    5.880988
1993-01-31    5.883418
1994-01-31    5.891457
1995-01-31    5.874904
1996-01-31    5.904625
1997-01-31    5.874011
1998-01-31    5.867364
1999-01-31    5.857447
2000-01-31    5.886688
2001-01-31    5.868525
2002-01-31    5.870507
2003-01-31    5.867206
2004-01-31    5.878360
2005-01-31    5.846219
2006-01-31    5.871577
2007-01-31    5.857414
2008-01-31    5.886432
2009-01-31    5.909441
2010-01-31    5.859429
2011-01-31    5.906801
2012-01-31    5.863766
2013-01-31    5.871167
2014-01-31    5.876190
2015-01-31    5.884719
2016-01-31    5.926201
2017-01-31    5.888056
Name: Magnitude, dtype: float64

In [22]:
# determine std deviation earthquakes Magnitudes in 12 month periods using 'resample()' with std()
df2['Magnitude'][df2.Type == 'Earthquake'].resample('12M').std()

Date_Time
1965-01-31    0.683318
1966-01-31    0.454213
1967-01-31    0.440944
1968-01-31    0.410671
1969-01-31    0.479872
1970-01-31    0.412309
1971-01-31    0.430897
1972-01-31    0.464987
1973-01-31    0.419704
1974-01-31    0.371009
1975-01-31    0.385333
1976-01-31    0.430614
1977-01-31    0.402297
1978-01-31    0.379903
1979-01-31    0.411788
1980-01-31    0.392342
1981-01-31    0.404997
1982-01-31    0.398501
1983-01-31    0.381398
1984-01-31    0.438739
1985-01-31    0.405411
1986-01-31    0.425022
1987-01-31    0.393275
1988-01-31    0.423271
1989-01-31    0.395629
1990-01-31    0.376860
1991-01-31    0.429076
1992-01-31    0.430069
1993-01-31    0.409164
1994-01-31    0.406829
1995-01-31    0.423134
1996-01-31    0.445196
1997-01-31    0.429527
1998-01-31    0.421216
1999-01-31    0.416395
2000-01-31    0.413840
2001-01-31    0.436487
2002-01-31    0.415136
2003-01-31    0.429939
2004-01-31    0.424789
2005-01-31    0.401266
2006-01-31    0.423383
2007-01-31    0.398057
2008-01-31    0.432334
2009-01-31    0.417207
2010-01-31    0.423196
2011-01-31    0.457307
2012-01-31    0.400249
2013-01-31    0.451289
2014-01-31    0.449676
2015-01-31    0.428857
2016-01-31    0.466576
2017-01-31    0.442928
Name: Magnitude, dtype: float64

In [23]:
# find when the largest (Magnitude = 9.1) earthquake occurred
df2.loc[df2['Magnitude'] == 9.1]

                     Latitude  Longitude        Type  Depth  Magnitude
Date_Time
2004-12-26 00:58:53     3.295     95.982  Earthquake   30.0        9.1
2011-03-11 05:46:24    38.297    142.373  Earthquake   29.0        9.1

In [24]:
# find when the smallest Depth (Depth = -1.1) earthquake occurred
df2.loc[df2['Depth'] == -1.1]

                     Latitude  Longitude        Type  Depth  Magnitude
Date_Time
1992-06-28 12:00:45    34.131   -116.408  Earthquake   -1.1       5.77

In [25]:
# find out how many nuclear explosions per year since 1965 (in dataset)
df2.index.year[df2.Type == 'Nuclear Explosion'].value_counts().sort_index()

Date_Time
1966.0     1
1968.0     2
1969.0     1
1970.0     1
1973.0     6
1974.0     6
1975.0     9
1976.0    10
1977.0     8
1978.0    15
1979.0    13
1980.0    13
1981.0     8
1982.0     6
1983.0    10
1984.0    14
1985.0     6
1986.0     1
1987.0    16
1988.0    10
1989.0     7
1990.0     4
1991.0     1
1992.0     1
1993.0     1
1994.0     2
1995.0     2
1996.0     1
Name: count, dtype: int64